#ifndef _IG_ELFPARSER_SECTHEAD_PRIV_H_
#define _IG_ELFPARSER_SECTHEAD_PRIV_H_

#define SECTHEADER_ENTRY_LEN 10

#define SECTHEADER_ENTRY_NAMEIDX_OFF            0x00u
#define SECTHEADER_ENTRY_TYPE_OFF               0x04u
#define SECTHEADER_ENTRY_FLAGS_OFF              0x08u
#define SECTHEADER_ENTRY_SECTADDR_OFF_32BIT     0x0Cu
#define SECTHEADER_ENTRY_SECTADDR_OFF_64BIT     0x10u
#define SECTHEADER_ENTRY_SECTOFF_OFF_32BIT      0x10u
#define SECTHEADER_ENTRY_SECTOFF_OFF_64BIT      0x18u
#define SECTHEADER_ENTRY_SECTSIZE_OFF_32BIT     0x14u
#define SECTHEADER_ENTRY_SECTSIZE_OFF_64BIT     0x20u
#define SECTHEADER_ENTRY_LINK_OFF_32BIT         0x18u
#define SECTHEADER_ENTRY_LINK_OFF_64BIT         0x28u
#define SECTHEADER_ENTRY_INFO_OFF_32BIT         0x1Cu
#define SECTHEADER_ENTRY_INFO_OFF_64BIT         0x2Cu
#define SECTHEADER_ENTRY_ADDRALIGN_OFF_32BIT    0x20u
#define SECTHEADER_ENTRY_ADDRALIGN_OFF_64BIT    0x30u
#define SECTHEADER_ENTRY_ENTRYSIZE_OFF_32BIT    0x24u
#define SECTHEADER_ENTRY_ENTRYSIZE_OFF_64BIT    0x38u

#define SECTHEADER_ENTRY_NAMEIDX_SIZE           4u
#define SECTHEADER_ENTRY_TYPE_SIZE              4u
#define SECTHEADER_ENTRY_FLAGS_SIZE_32BIT       4u
#define SECTHEADER_ENTRY_FLAGS_SIZE_64BIT       8u
#define SECTHEADER_ENTRY_SECTADDR_SIZE_32BIT    4u
#define SECTHEADER_ENTRY_SECTADDR_SIZE_64BIT    8u
#define SECTHEADER_ENTRY_SECTOFF_SIZE_32BIT     4u
#define SECTHEADER_ENTRY_SECTOFF_SIZE_64BIT     8u
#define SECTHEADER_ENTRY_SECTSIZE_SIZE_32BIT    4u
#define SECTHEADER_ENTRY_SECTSIZE_SIZE_64BIT    8u
#define SECTHEADER_ENTRY_LINK_SIZE              4u
#define SECTHEADER_ENTRY_INFO_SIZE              4u
#define SECTHEADER_ENTRY_ADDRALIGN_SIZE_32BIT   4u
#define SECTHEADER_ENTRY_ADDRALIGN_SIZE_64BIT   8u
#define SECTHEADER_ENTRY_ENTRYSIZE_SIZE_32BIT   4u
#define SECTHEADER_ENTRY_ENTRYSIZE_SIZE_64BIT   8u

#endif /* _IG_ELFPARSER_SECTHEAD_PRIV_H_ */